/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Files {
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  parent_id: string;
  size: Int8;
  updated_at: Timestamp;
}

export interface FolderFiles {
  file: string;
  folder: string;
}

export interface FolderFolders {
  child_folder: string;
  parent_folder: string;
}

export interface Folders {
  deleted_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  parent_id: string | null;
}

export interface DB {
  files: Files;
  folder_files: FolderFiles;
  folder_folders: FolderFolders;
  folders: Folders;
}
